workflows:
  release_build:
    name: Release Build for Android + iOS + Web
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

      groups:
        # Add your Apple signing credentials inside Codemagic UI under this group
        - app_store_credentials

      vars:
        APP_LOCATION: "."
        SUPABASE_URL: "https://bczovurgxkhphtdzdxos.supabase.co"
      secure:
        SUPABASE_ANON_KEY: Encrypted_supabase_key_here

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true

    scripts:
      # 1️⃣ Install dependencies
      - name: Install Flutter packages
        script: |
          flutter pub get

      # 2️⃣ Build Android AAB (Play Store)
      - name: Build Android AppBundle (Release)
        script: |
          flutter build appbundle \
            --release \
            --dart-define=SUPABASE_URL=$SUPABASE_URL \
            --dart-define=SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY

      # 3️⃣ Build iOS IPA (TestFlight/App Store)
      - name: Build iOS IPA (Release)
        script: |
          flutter build ipa \
            --release \
            --export-options-plist=ios/ExportOptions.plist \
            --dart-define=SUPABASE_URL=$SUPABASE_URL \
            --dart-define=SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY

      # 4️⃣ Build Web App
      - name: Build Web Release
        script: |
          flutter build web --release \
            --dart-define=SUPABASE_URL=$SUPABASE_URL \
            --dart-define=SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY
          zip -r web_release.zip build/web

    artifacts:
      - build/**/app-release.aab
      - build/**/Runner.ipa
      - web_release.zip

    publishing:
      # Optional — enable if you want auto-upload
      app_store_connect:
        apple_id: $APPLE_ID
        api_key_id: $APP_STORE_API_KEY_ID
        api_key: $APP_STORE_API_PRIVATE_KEY
        submit_to_testflight: true
        notify_testers: true
